import 'package:flutter/material.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:form_builder_validators/form_builder_validators.dart';
import 'package:go_router/go_router.dart';
import 'package:mobile/common/widgets/custom_button.dart';
import 'package:mobile/common/widgets/custom_text_field.dart';
import 'package:mobile/common/widgets/empty_state.dart';
import 'package:mobile/common/widgets/loading_indicator.dart';
import 'package:mobile/core/colors/app_colors.dart';
import 'package:mobile/core/constants/text_styles.dart';
import 'package:mobile/features/profile/data/models/address_model.dart';
import 'package:mobile/features/profile/domain/providers/profile_provider.dart';

class AddressScreen extends ConsumerStatefulWidget {
  const AddressScreen({super.key});

  @override
  ConsumerState<AddressScreen> createState() => _AddressScreenState();
}

class _AddressScreenState extends ConsumerState<AddressScreen> {
  final _formKey = GlobalKey<FormBuilderState>();

  void _showAddAddressModal(BuildContext context) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: AppColors.white,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(24.r)),
      ),
      builder: (ctx) {
        return Padding(
          padding: EdgeInsets.only(
            bottom: MediaQuery.of(ctx).viewInsets.bottom,
            left: 24.w,
            right: 24.w,
            top: 24.h,
          ),
          child: FormBuilder(
            key: _formKey,
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Add New Address',
                  style: customTextStyles['sb20']?.copyWith(
                    color: AppColors.black,
                  ),
                ),
                SizedBox(height: 24.h),
                CustomTextField(
                  name: 'street',
                  label: 'Street Address',
                  hintText: 'Enter street',
                  validator: FormBuilderValidators.required(),
                ),
                SizedBox(height: 16.h),
                Row(
                  children: [
                    Expanded(
                      child: CustomTextField(
                        name: 'city',
                        label: 'City',
                        hintText: 'City',
                        validator: FormBuilderValidators.required(),
                      ),
                    ),
                    SizedBox(width: 16.w),
                    Expanded(
                      child: CustomTextField(
                        name: 'pincode',
                        label: 'Pincode',
                        hintText: 'Pincode',
                        keyboardType: TextInputType.number,
                        validator: FormBuilderValidators.compose([
                          FormBuilderValidators.required(),
                          FormBuilderValidators.numeric(),
                        ]),
                      ),
                    ),
                  ],
                ),
                SizedBox(height: 16.h),
                FormBuilderSwitch(
                  name: 'isDefault',
                  title: Text(
                    'Set as default address',
                    style: customTextStyles['sb14']?.copyWith(
                      color: AppColors.black,
                    ),
                  ),
                  initialValue: false,
                  decoration: const InputDecoration(border: InputBorder.none),
                  activeColor: AppColors.blue500,
                ),
                SizedBox(height: 32.h),
                CustomButton(
                  title: 'Save Address',
                  onPressed: () async {
                    if (_formKey.currentState?.saveAndValidate() ?? false) {
                      final data = _formKey.currentState!.value;
                      final address = AddressModel(
                        id: '', // Empty, generated by backend
                        street: data['street'],
                        city: data['city'],
                        pincode: data['pincode'],
                        isDefault: data['isDefault'],
                      );

                      final success = await ref
                          .read(addressNotifierProvider.notifier)
                          .addAddress(address);
                      if (success && mounted) {
                        Navigator.pop(ctx);
                      } else {
                        ScaffoldMessenger.of(context).showSnackBar(
                          const SnackBar(
                            content: Text('Failed to add address'),
                          ),
                        );
                      }
                    }
                  },
                ),
                SizedBox(height: 40.h),
              ],
            ),
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final addressesAsync = ref.watch(addressNotifierProvider);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text(
          'My Addresses',
          style: customTextStyles['sb20']?.copyWith(color: AppColors.white),
        ),
        backgroundColor: AppColors.dark,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(
            Icons.arrow_back_ios,
            color: AppColors.white,
            size: 20,
          ),
          onPressed: () => context.pop(),
        ),
      ),
      body: addressesAsync.when(
        data: (addresses) {
          if (addresses.isEmpty) {
            return EmptyState(
              icon: Icons.location_off_outlined,
              title: 'No Addresses Found',
              subtitle: 'You haven\'t added any delivery addresses yet.',
              actionButton: CustomButton(
                title: 'Add New Address',
                onPressed: () => _showAddAddressModal(context),
              ),
            );
          }

          return ListView.separated(
            padding: EdgeInsets.all(24.w),
            itemCount: addresses.length,
            separatorBuilder: (context, index) => SizedBox(height: 16.h),
            itemBuilder: (context, index) {
              final addr = addresses[index];
              return Container(
                padding: EdgeInsets.all(20.w),
                decoration: BoxDecoration(
                  color: AppColors.dark,
                  borderRadius: BorderRadius.circular(16.r),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          'Address ${index + 1}',
                          style: customTextStyles['sb16']?.copyWith(
                            color: AppColors.white,
                          ),
                        ),
                        if (addr.isDefault)
                          Container(
                            padding: EdgeInsets.symmetric(
                              horizontal: 8.w,
                              vertical: 4.h,
                            ),
                            decoration: BoxDecoration(
                              color: AppColors.blue500.withOpacity(0.2),
                              borderRadius: BorderRadius.circular(4.r),
                            ),
                            child: Text(
                              'Default',
                              style: customTextStyles['sb12']?.copyWith(
                                color: AppColors.blue500,
                              ),
                            ),
                          ),
                      ],
                    ),
                    SizedBox(height: 12.h),
                    Text(
                      addr.street,
                      style: customTextStyles['r14']?.copyWith(
                        color: AppColors.normalText,
                      ),
                    ),
                    Text(
                      '${addr.city} - ${addr.pincode}',
                      style: customTextStyles['r14']?.copyWith(
                        color: AppColors.normalText,
                      ),
                    ),
                  ],
                ),
              );
            },
          );
        },
        loading: () => const Center(child: LoadingIndicator()),
        error: (err, stack) => Center(
          child: Text('Error: $err', style: TextStyle(color: AppColors.red500)),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        backgroundColor: AppColors.blue500,
        onPressed: () => _showAddAddressModal(context),
        child: const Icon(Icons.add, color: AppColors.white),
      ),
    );
  }
}
